FROM keymetrics/pm2:18-alpine

# bash 설치
RUN apk add --no-cache bash

# 환경 변수 설정
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV} \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# 필요한 패키지와 종속성 설치
RUN echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
    echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache \
        nmap \
        chromium \
        harfbuzz \
        freetype \
        ttf-freefont \
        nss \
        dbus \
        dbus-x11 \
        libxcomposite \
        libxi \
        libxtst \
        libxscrnsaver \
        libxrandr \
        udev \
        xvfb \
        x11vnc \
        fluxbox \
        ca-certificates \
        && rm -rf /var/cache/* \
        && mkdir /var/cache/apk

# D-Bus 디렉토리 생성 및 설정
RUN mkdir -p /var/run/dbus && \
    dbus-uuidgen > /var/lib/dbus/machine-id

EXPOSE 4001

WORKDIR /app

# 애플리케이션 종속성 설치
COPY ./package*.json ./
RUN npm install --production

# 애플리케이션 코드 복사
COPY ./ ./

CMD ["sh", "-c", "NODE_ENV=$NODE_ENV pm2-runtime --json pm2Server.json"]
